# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  sam: circleci/aws-serverless@1.0.1
jobs:
  build:
    machine: true
    executor: sam/default
    steps:
      - run:
          name: Install bazel
          command: |-
            sudo apt install curl gnupg
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            sudo apt update && sudo apt install bazel
      - checkout
      - run:
          name: Build weather service
          command: |-
            echo "build weather service"
            bazel build src/main/java/com/weather:weather-service_deploy.jar
      - sam/install
      - run: sam deploy --s3-bucket helloworld-deploy --stack-name api-stack --capabilities CAPABILITY_IAM --template-file src/main/java/com/weather/template.yaml
workflows:
  welcome:
    jobs:
      - build
